### ISSUE TITLE
AppConfigWithTargetPath with duplicated value

### ISSUE THREAD

**Issue by McXX** [golavr/ConfigurationTransform#8]
The AfterCompile target created contains AppConfigWithTargetPath changes which remove App.config and add transformed .config.

This seems to sometimes malfunction on VS 2017 (15.6.1) as AppConfigWithTargetPath is reused - the transformed .config is added twice, and target "GenerateApplicationManifest" fails on "ConfigFile" (Microsoft.Common.CurrentVersion.targets(3812,9): error MSB4094).

This may be corrected for example by not adding twice the same .config 
`<AppConfigWithTargetPath Include="$(IntermediateOutputPath)$(TargetFileName).config" KeepDuplicates="false">`

**Comment by snekbaev** [comment]
Hi,

installed the plugin, created config, added the transformation file and tried to build:
```
Error MSB4094: "obj\redacted - test (Azure)\redacted.exe.config;obj\redacted - test (Azure)\redacted.exe.config" is an invalid value for the "ConfigFile" parameter of the "GenerateApplicationManifest" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem". (1, 1)
```
is this related?

Thank you!

**Comment by snekbaev** [comment]
interesting enough that unchecking the ClickOnce security settings in the project settings seems to resolve the matter...

**Comment by NightOwl888** [comment]
I found another way to resolve this.

As per the [Crystal Reports ClickOnce documentation](https://help.sap.com/viewer/0d6684e153174710b8b2eb114bb7f843/SP21/en-US/45b3096a6e041014910aba7db0e91070.html):

> 1. In the Solution Explorer, right-click the bold project name, and click Properties.
Click on the Security tab.
> 2. Select Enable ClickOnce Security Settings.
> 3. By default, the ClickOnce security permission is set to This is a full trust application.

However, when doing so, it creates this same problem with the project changes that ConfigurationTransform adds. 

> "obj\debug\project.exe.config;obj\Debug\project.exe.config" is an invalid value for the "ConfigFile" parameter of the "GenerateApplicationManifest" task.

In my case, reverting the security permissions is not an option. However, [this StackOverflow answer](https://stackoverflow.com/a/53518983) seems to resolve the problem by fixing up the XML that ConfigurationTransform creates. To fix, change:

```xml
<AppConfigWithTargetPath Remove="App.config" />
```
To:
```xml
<AppConfigWithTargetPath Remove="@(AppConfigWithTargetPath)" />
```

Ideally, this plugin would be fixed to ensure this error doesn't happen rather than having to manually fix it in every ClickOnce project.
